language: python
matrix:
    include:
        -   env: TOXENV=py27 GO=1.10
        -   env: TOXENV=py27 GO=1.11
        -   env: TOXENV=py36 GO=1.11
            python: 3.6
        -   env: TOXENV=pypy GO=1.11
            python: pypy
install:
    - eval "$(gimme $GO)"
    - pip install coveralls tox
script: tox
after_success: TOP=. coveralls
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.cache/pre-commit
